# app/deps.py

from fastapi import Depends, HTTPException
from fastapi.security import HTTPBearer
from sqlalchemy.orm import Session
from jose import jwt, JWTError
import os

from app.db import get_db
from app.models import User

oauth2_scheme = HTTPBearer(auto_error=True)

JWT_SECRET = os.getenv("JWT_SECRET", "localdevsecret")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "HS256")


def get_current_user(
    token: str = Depends(oauth2_scheme),
    db: Session = Depends(get_db)
):
    """
    Validates JWT generated by /v1/auth/email/verify-otp
    Returns full User model or 404 for new users.
    """

    try:
        payload = jwt.decode(
            token.credentials,
            JWT_SECRET,
            algorithms=[JWT_ALGORITHM]
        )

        email = payload.get("email")
        if not email:
            raise HTTPException(401, "Invalid token payload")

    except JWTError:
        raise HTTPException(401, "Invalid or expired token")

    user = db.query(User).filter(User.email == email).first()

    if not user:
        # New OTP login → no user row yet → force onboarding
        raise HTTPException(
            status_code=404,
            detail="New user onboarding required"
        )

    return user
